// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppData matches the API response and local storage format.
 * Updated to match current API: removed old ports, added XHTTP, Reality, Hysteria.
 */
export class AppData {
    /**
     * Creates a new AppData instance.
     * @param {Partial<AppData>} [$$source = {}] - The source object to create the AppData.
     */
    constructor($$source = {}) {
        if (!("userData" in $$source)) {
            /**
             * @member
             * @type {any}
             */
            this["userData"] = null;
        }
        if (!("locations" in $$source)) {
            /**
             * @member
             * @type {LocationInfo[]}
             */
            this["locations"] = [];
        }
        if (!("user_uuid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user_uuid"] = "";
        }
        if (!("sessionName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionName"] = "";
        }
        if (!("latestAppVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestAppVersion"] = "";
        }
        if (!("protocol" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["protocol"] = "";
        }
        if (!("isMini" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isMini"] = false;
        }
        if (!("enableTor" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableTor"] = false;
        }
        if (!("useCustomLink" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["useCustomLink"] = false;
        }
        if (!("customV2rayLink" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["customV2rayLink"] = "";
        }
        if (!("selectedLocationName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["selectedLocationName"] = "";
        }
        if (!("splitTunnelEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["splitTunnelEnabled"] = false;
        }
        if (!("splitTunnelDomains" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["splitTunnelDomains"] = "";
        }
        if (!("splitTunnelDiscord" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["splitTunnelDiscord"] = false;
        }
        if (!("splitTunnelSteam" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["splitTunnelSteam"] = false;
        }
        if (!("splitTunnelCustom" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["splitTunnelCustom"] = "";
        }
        if (!("splitTunnelMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["splitTunnelMode"] = "";
        }
        if (!("autoStart" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoStart"] = false;
        }
        if (!("autoConnect" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoConnect"] = false;
        }
        if (!("killSwitch" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["killSwitch"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppData}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("locations" in $$parsedSource) {
            $$parsedSource["locations"] = $$createField1_0($$parsedSource["locations"]);
        }
        return new AppData(/** @type {Partial<AppData>} */($$parsedSource));
    }
}

export class AppSessionInfo {
    /**
     * Creates a new AppSessionInfo instance.
     * @param {Partial<AppSessionInfo>} [$$source = {}] - The source object to create the AppSessionInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSessionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSessionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSessionInfo(/** @type {Partial<AppSessionInfo>} */($$parsedSource));
    }
}

/**
 * ConnectionStatus represents the result of waiting for VPN connection
 */
export class ConnectionStatus {
    /**
     * Creates a new ConnectionStatus instance.
     * @param {Partial<ConnectionStatus>} [$$source = {}] - The source object to create the ConnectionStatus.
     */
    constructor($$source = {}) {
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("ipChanged" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ipChanged"] = false;
        }
        if (!("ipInfo" in $$source)) {
            /**
             * @member
             * @type {IPInfo}
             */
            this["ipInfo"] = (new IPInfo());
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionStatus}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ipInfo" in $$parsedSource) {
            $$parsedSource["ipInfo"] = $$createField2_0($$parsedSource["ipInfo"]);
        }
        return new ConnectionStatus(/** @type {Partial<ConnectionStatus>} */($$parsedSource));
    }
}

export class DeleteSessionResult {
    /**
     * Creates a new DeleteSessionResult instance.
     * @param {Partial<DeleteSessionResult>} [$$source = {}] - The source object to create the DeleteSessionResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AppSessionInfo[] | undefined}
             */
            this["sessions"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteSessionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeleteSessionResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField2_0($$parsedSource["sessions"]);
        }
        return new DeleteSessionResult(/** @type {Partial<DeleteSessionResult>} */($$parsedSource));
    }
}

export class IPInfo {
    /**
     * Creates a new IPInfo instance.
     * @param {Partial<IPInfo>} [$$source = {}] - The source object to create the IPInfo.
     */
    constructor($$source = {}) {
        if (!("query" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["query"] = "";
        }
        if (!("country" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["country"] = "";
        }
        if (!("countryCode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["countryCode"] = "";
        }
        if (!("city" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["city"] = "";
        }
        if (!("lat" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lat"] = 0;
        }
        if (!("lon" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lon"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IPInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IPInfo(/** @type {Partial<IPInfo>} */($$parsedSource));
    }
}

/**
 * LocationInfo - synced with API. Removed old VlessPort/VmessPort/TrojanPort.
 * Added VlessXhttpPort, VlessRealityPort, HysteriaPort, etc.
 */
export class LocationInfo {
    /**
     * Creates a new LocationInfo instance.
     * @param {Partial<LocationInfo>} [$$source = {}] - The source object to create the LocationInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["domain"] = "";
        }
        if (!("ip_address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip_address"] = "";
        }
        if (!("vless_xhttp_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["vless_xhttp_port"] = 0;
        }
        if (!("vmess_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["vmess_port"] = 0;
        }
        if (!("trojan_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["trojan_port"] = 0;
        }
        if (!("vless_xtls_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["vless_xtls_port"] = 0;
        }
        if (!("reality_pk" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reality_pk"] = "";
        }
        if (!("vless_reality_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["vless_reality_port"] = 0;
        }
        if (!("vless_xtls_tor_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["vless_xtls_tor_port"] = 0;
        }
        if (!("hysteria_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hysteria_port"] = 0;
        }
        if (!("hysteria_salamander" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hysteria_salamander"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocationInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocationInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocationInfo(/** @type {Partial<LocationInfo>} */($$parsedSource));
    }
}

export class LocationWithPing {
    /**
     * Creates a new LocationWithPing instance.
     * @param {Partial<LocationWithPing>} [$$source = {}] - The source object to create the LocationWithPing.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("rttMillis" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rttMillis"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocationWithPing instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocationWithPing}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocationWithPing(/** @type {Partial<LocationWithPing>} */($$parsedSource));
    }
}

export class LoginResult {
    /**
     * Creates a new LoginResult instance.
     * @param {Partial<LoginResult>} [$$source = {}] - The source object to create the LoginResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["sessionName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AppSessionInfo[] | undefined}
             */
            this["sessions"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoginResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoginResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField3_0($$parsedSource["sessions"]);
        }
        return new LoginResult(/** @type {Partial<LoginResult>} */($$parsedSource));
    }
}

export class StartupData {
    /**
     * Creates a new StartupData instance.
     * @param {Partial<StartupData>} [$$source = {}] - The source object to create the StartupData.
     */
    constructor($$source = {}) {
        if (!("isLoggedIn" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isLoggedIn"] = false;
        }
        if (!("initialAppData" in $$source)) {
            /**
             * @member
             * @type {AppData}
             */
            this["initialAppData"] = (new AppData());
        }
        if (!("appVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appVersion"] = "";
        }
        if (!("isUpdateAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isUpdateAvailable"] = false;
        }
        if (!("ipInfo" in $$source)) {
            /**
             * @member
             * @type {IPInfo}
             */
            this["ipInfo"] = (new IPInfo());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartupData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StartupData}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType5;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("initialAppData" in $$parsedSource) {
            $$parsedSource["initialAppData"] = $$createField1_0($$parsedSource["initialAppData"]);
        }
        if ("ipInfo" in $$parsedSource) {
            $$parsedSource["ipInfo"] = $$createField4_0($$parsedSource["ipInfo"]);
        }
        return new StartupData(/** @type {Partial<StartupData>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = LocationInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = IPInfo.createFrom;
const $$createType3 = AppSessionInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = AppData.createFrom;
