// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * VPNService is the main application service exposed to the frontend via Wails 3 bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function BrowserOpenURL(url) {
    return $Call.ByID(189183088, url);
}

/**
 * @param {string} username
 * @param {string} password
 * @param {number} sessionIDToDelete
 * @returns {$CancellablePromise<$models.DeleteSessionResult>}
 */
export function DeleteSessionWithCredentials(username, password, sessionIDToDelete) {
    return $Call.ByID(4045914432, username, password, sessionIDToDelete).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function FindFastestLocation() {
    return $Call.ByID(1194237035);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetAutoStart() {
    return $Call.ByID(565202276);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetCoreStatus() {
    return $Call.ByID(1019146378);
}

/**
 * @returns {$CancellablePromise<$models.LocationWithPing[]>}
 */
export function GetLocationsWithPing() {
    return $Call.ByID(2358288829).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.IPInfo>}
 */
export function GetMyIP() {
    return $Call.ByID(1749526928).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function LoadAppData() {
    return $Call.ByID(3701203596);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function LoadFile() {
    return $Call.ByID(3734384971);
}

/**
 * @param {string} username
 * @param {string} password
 * @returns {$CancellablePromise<$models.LoginResult>}
 */
export function Login(username, password) {
    return $Call.ByID(1483623302, username, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function LogoutAndForget() {
    return $Call.ByID(3704698329);
}

/**
 * @param {string} appDataJson
 * @returns {$CancellablePromise<void>}
 */
export function SaveAppData(appDataJson) {
    return $Call.ByID(3351003935, appDataJson);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetAutoStart(enabled) {
    return $Call.ByID(3140972504, enabled);
}

/**
 * @param {boolean} isMini
 * @returns {$CancellablePromise<void>}
 */
export function SetMiniMode(isMini) {
    return $Call.ByID(1967698779, isMini);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(1501898711);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function StartCore() {
    return $Call.ByID(4243350248);
}

/**
 * @returns {$CancellablePromise<$models.StartupData>}
 */
export function StartupCheck() {
    return $Call.ByID(1802078614).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function StopCore() {
    return $Call.ByID(272711114);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ValidateSession() {
    return $Call.ByID(292639977);
}

/**
 * WaitForConnection waits for core.exe to start AND for the IP to change.
 * It takes the old IP (before VPN) and tries up to ~30 seconds to detect a new IP.
 * Returns immediately if core.exe is not running.
 * @param {string} oldIP
 * @returns {$CancellablePromise<$models.ConnectionStatus>}
 */
export function WaitForConnection(oldIP) {
    return $Call.ByID(1527923075, oldIP).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.DeleteSessionResult.createFrom;
const $$createType1 = $models.LocationWithPing.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.IPInfo.createFrom;
const $$createType4 = $models.LoginResult.createFrom;
const $$createType5 = $models.StartupData.createFrom;
const $$createType6 = $models.ConnectionStatus.createFrom;
